var firstname="dinesh";
var lastname="palani";
var maritalstatus="single";
var age="24";
var country="india";
console.log(firstname);
console.log(lastname);
console.log(maritalstatus);
console.log(age);
console.log(country);
